version: '3.8'

networks:
  fini-network:
    driver: bridge
    name: fini-network

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

      - "--api.insecure=true"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - fini-network
    restart: always

  fini-server:
    image: ${AWS_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/fini-repo:latest
    platform: linux/amd64
    container_name: fini-server
    environment:
      - TZ=Asia/Seoul
    networks:
      - fini-network
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fini-router.rule=Host(`api.finiapp.tech`)"
      - "traefik.http.routers.fini-router.entrypoints=web"
      - "traefik.http.routers.fini-router.service=fini-service"
      - "traefik.http.services.fini-service.loadbalancer.server.port=8080"